export const browserCoreExamples = [
  "civitas browser status",
  "civitas browser start",
  "civitas browser stop",
  "civitas browser tabs",
  "civitas browser open https://example.com",
  "civitas browser focus abcd1234",
  "civitas browser close abcd1234",
  "civitas browser screenshot",
  "civitas browser screenshot --full-page",
  "civitas browser screenshot --ref 12",
  "civitas browser snapshot",
  "civitas browser snapshot --format aria --limit 200",
  "civitas browser snapshot --efficient",
  "civitas browser snapshot --labels",
];

export const browserActionExamples = [
  "civitas browser navigate https://example.com",
  "civitas browser resize 1280 720",
  "civitas browser click 12 --double",
  'civitas browser type 23 "hello" --submit',
  "civitas browser press Enter",
  "civitas browser hover 44",
  "civitas browser drag 10 11",
  "civitas browser select 9 OptionA OptionB",
  "civitas browser upload /tmp/civitas/uploads/file.pdf",
  'civitas browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "civitas browser dialog --accept",
  'civitas browser wait --text "Done"',
  "civitas browser evaluate --fn '(el) => el.textContent' --ref 7",
  "civitas browser console --level error",
  "civitas browser pdf",
];
